// <auto-generated />
using ApiCoreClientEgitim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiCoreClientEgitim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521152517_CreatDb")]
    partial class CreatDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiCoreClientEgitim.Data.Egitmenler", b =>
                {
                    b.Property<int>("EgitmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdiSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EgitmenId");

                    b.ToTable("Egitmenler");
                });

            modelBuilder.Entity("ApiCoreClientEgitim.Data.Katilimcilar", b =>
                {
                    b.Property<int>("KatilimciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatilimciId");

                    b.ToTable("Katilimcilar");
                });

            modelBuilder.Entity("ApiCoreClientEgitim.Data.KursKatilim", b =>
                {
                    b.Property<int>("KursKatilimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaslangicTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BitisTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KatilimciId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.HasKey("KursKatilimId");

                    b.HasIndex("KatilimciId");

                    b.HasIndex("KursId");

                    b.ToTable("KursKatilim");
                });

            modelBuilder.Entity("ApiCoreClientEgitim.Data.Kurslar", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EgitimenId")
                        .HasColumnType("int");

                    b.Property<string>("KursAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KursAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KursSuresi")
                        .HasColumnType("int");

                    b.Property<int>("KursUcreti")
                        .HasColumnType("int");

                    b.HasKey("KursId");

                    b.HasIndex("EgitimenId");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("ApiCoreClientEgitim.Data.KursKatilim", b =>
                {
                    b.HasOne("ApiCoreClientEgitim.Data.Katilimcilar", "Katilimcilar")
                        .WithMany()
                        .HasForeignKey("KatilimciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCoreClientEgitim.Data.Kurslar", "Kurslar")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katilimcilar");

                    b.Navigation("Kurslar");
                });

            modelBuilder.Entity("ApiCoreClientEgitim.Data.Kurslar", b =>
                {
                    b.HasOne("ApiCoreClientEgitim.Data.Egitmenler", "Egitmenler")
                        .WithMany()
                        .HasForeignKey("EgitimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egitmenler");
                });
#pragma warning restore 612, 618
        }
    }
}
